travis:
  secure:
    BINSTAR_TOKEN: xPsHSm0GMbCRGd9TwCIHvK1FI27DI8iWd2hLicvb8/D3p34Yy/3xEEi2qy1F4wBelqGaYN38RSOi65c+gUQNpgsnjIjKSnq59a4tTWP5hlks6tas3N2QAfE1wq5n520v/6wmx5vXE4J7KO9UXnFqAw6ENKzsFMmHMobwCydZmUBQyy1a71zcNDKdwD8dgZiasFT5cKWDBTT7Diwb5dNzD+zZtgEkNywXextxqQU2x7rbH3rWw7BIxjsYdxD+pgrbRTfBNhvUqzYJUMYSw/Zzmx46UBDTsM+/GvIdwnZiCA8ZdUu3av9V5FIeJc80MfExXflRszFCH+zfCdrdZPhRamrIU3yJhciuhVcJ6yACb6G+5YLxk8Sjbt7rvZSU4nNr6DzL/dedlHRg0yKgJE5IGOB7/mbXwPi2x8k/2zGq6cARi9I7HwdrnQp5cJiqL8QRGFQJCx3p0ug3OB2u3jJZSq+fffnBRaMuBRNAbe52TXE97S0Oc7vLlV95eEl2cO20WtjhL+w/2dWlF0VisKa/XWkMhoYkarMkyHm358T1OpHLMzqhouVDhvho2CvtjgaQj2IveeO03xCUYDFW85emSIX8UBnXfUf4QC8wBnixFpaIQCzEO/iVwI9t6IYba3wV1nK/Gflan0TRgRmP9IVZ5nMy8dkLIsGZMboQxEjDp/w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
